### ISSUE TITLE
Call for an emergency vote to push back every stage of ANV4 by 1 week

### ISSUE THREAD

**Issue by burrrata** [aragon/AGPs#114]
## Overview

ANV4 is the first time using the new AGP format of:
- proposal => community review => AA review => final freeze => vote 

This new process is significantly more complex than before. Considering that [the majority of AGPs this round were closed](https://github.com/aragon/AGPs/pulls?q=is%3Apr+is%3Aclosed), that should give us pause. We went from having around 20 APG PRs to 3. Obviously this process was not very well understood. The reason for most of these cancellations is that people did not mark their AGPs as "finalized." It would seem reasonable that the AGP editors might see this and realize there was a problem. Perhaps an announcement saying: "Hey! less than 72 hours before you need to finalize AGPs." would help. Maybe commenting on PRs reminding authors that they need to "finalize" their proposals to pass to the next stage. Lots of things could have made this process a success, but it was not.

In addition to confusion surrounding the process itself, AA put in the bulk of their comments/feedback less than 24 hours before the vote! This does not give AGP authors a lot of time to take feedback into consideration, respond, and make changes. Considering that the Aragon community is global and has to deal with multiple time zones, this is simply not considerate. The Aragon Governance Process is the foundation of Aragon, but my impression is that this ANV was not a priority for the AA.

In addition to all that, the process of submitting GitHub PRs broke. Many people, myself included, were not able to edit their proposals after submitting a PR. This is likely due to a bug in the GitHub PR system. If the process we use for governance is broken, how are we supposed to function as a community?

<br>

## Further Analysis

If you have a governance process that is not clearly specified, how is the community supposed to participate?

If you have a governance process that relies on infrastructure that is not reliable, how is the community supposed to participate?

We cannot have clear and fair governance if the governance process is not clear and fair. 

### What is "finalization?" 
The updated [AGP-1](https://github.com/aragon/AGPs/blob/master/AGPs/AGP-1.md) says:
- "After a proposal in Stage IV has been thoroughly reviewed, you may finalize your proposal and request that an AGP Editor moves the proposal from Stage IV to Stage V. If you do not finalize the proposal and request to move the proposal to Stage V before Stage V is scheduled to begin, AGP Editors will consider the proposal withdrawn and close the pull request when Stage V begins."

This is terribly ambiguous. What is the process to "finalize" a proposal? This was never specified. As a result, if we look at the open and merged AGPs we see that there was no consensus or consistency in the way AGPs were approved.

### Governance Infrastructure
The infrastructure we are using for the Aragon governance process broke. Many people were not able to edit or update AGP PRs after submission. 
- For a more detailed explanation of the situation, take a look at [this GitHub PR](https://github.com/aragon/AGPs/pull/100#event-2703400906). GitHub shows a commit from `unknown repository` and does not allow for changes to that commit.

This affected multiple AGPs, not just the example above. As a result not all AGP authors were able to participate in ANV4 with equal opportunity. This is not ok. 

### Looking at [the AGPs that were not closed](https://github.com/aragon/AGPs/pulls), we see the following:
- [AGP PR 102](https://github.com/aragon/AGPs/pull/102): A comment says that the proposal was updated, but no mention of finalization.
- [AGP PR 65](https://github.com/aragon/AGPs/pull/65): A comment says that this AGP is is not finalized and should be left open as a draft.
- [AGP PR 60](https://github.com/aragon/AGPs/pull/60): No comments.

### Looking at [the AGPs that were closed and merged](https://github.com/aragon/AGPs/pulls?q=is%3Apr+is%3Aclosed), we see the following:
- [AGP PR 113](https://github.com/aragon/AGPs/pull/113): No comments.
- [AGP PR 112](https://github.com/aragon/AGPs/pull/112): A comment states technical difficulties, but do not state anything about "finalization."
- [AGP PR 106](https://github.com/aragon/AGPs/pull/106); A comment was made asking to move the AGP to stage v, but does not state anything about "finalization."
- [AGP PR 103](https://github.com/aragon/AGPs/pull/103): A comment was made stating that the proposal is finalized, please move to stage v.
- [AGP PR 89](https://github.com/aragon/AGPs/pull/89): A comment was made stating the proposal is finalized and can be moved to stage v.

We can clearly see that there is no consensus as to how an AGP is supposed to be marked as finalized. Various methods were used, none of which were clearly documented or followed by the majority of AGP authors. This is simply not acceptable for a governance process.

### Looking at [the AGPs that were closed and not merged](https://github.com/aragon/AGPs/pulls?q=is%3Apr+is%3Aclosed), we see the following:
- [AGP PR 111](https://github.com/aragon/AGPs/pull/111): No comments.
- [AGP PR 110](https://github.com/aragon/AGPs/pull/110): This PR was created 5 hours before the AGP "finalization" deadline. This PR was created by an AGP editor, but not by the original author. A comment states that this was an attempt to work around a bug in the GitHub PR system. 
    - This process of re-submitting PRs for original AGP authors to comment on is not standard practice, nor is it documented.
    - This new PR was submitted 5 hours before the AGP "finalization" deadline. 
    - AGP editor closed the AGP due to not being "finalized," even though there is no clear documented protocol to "finalize" an AGP.
- [AGP PR 109](https://github.com/aragon/AGPs/pull/109): This PR was created 5 hours before the AGP "finalization" deadline. This PR was created by an AGP editor, but not by the original author. A comment states that this was an attempt to work around a bug in the GitHub PR system. 
    - This process of re-submitting PRs for original AGP authors to comment on is not standard practice, nor is it documented.
    - This new PR was submitted 5 hours before the AGP "finalization" deadline. 
    - AGP editor closed the AGP due to not being "finalized," even though there is no clear documented protocol to "finalize" an AGP.
- [AGP PR 108](https://github.com/aragon/AGPs/pull/108): Comments were made by an AA member 10 hours before the "finalization" deadline. AGP editor closed the AGP due to not being "finalized," even though there is no clear documented protocol to "finalize" an AGP.
- [ AGP PR 107](https://github.com/aragon/AGPs/pull/107): All comments and reviews were created less than 24 hours before the "finalization" deadline. AGP editor closed the AGP due to not being "finalized," even though there is no clear documented protocol to "finalize" an AGP.
- [AGP PR 105](https://github.com/aragon/AGPs/pull/105): AGP editor reviews were created less than 5 hours before the "finalization" deadline. AGP editor closed the AGP due to not being "finalized," even though there is no clear documented protocol to "finalize" an AGP.
- [AGP PR 104](https://github.com/aragon/AGPs/pull/104): Comments and reviews by the AA and AGP editors were made 10 hours before the "finalization" deadline. AGP editor closed the AGP due to not being "finalized," even though there is no clear documented protocol to "finalize" an AGP.
- [AGP PR 101](https://github.com/aragon/AGPs/pull/101): Comments were made by an AA member 10 hours before the "finalization" deadline. AGP editor closed the AGP due to not being "finalized," even though there is no clear documented protocol to "finalize" an AGP.
- [AGP PR 100](https://github.com/aragon/AGPs/pull/100): Author stated 2 days before "finalization" deadline that the infrastructure to edit AGPs was not working correctly. No solution was provided. AGP was closed due to not being "finalized," even though there is no clear documented protocol to "finalize" an AGP.
- [AGP PR 99](https://github.com/aragon/AGPs/pull/99): Closed by AGP editor. No comment.
- [AGP PR 98](https://github.com/aragon/AGPs/pull/98): Closed by AGP editor. No comment.
- [AGP PR 97](https://github.com/aragon/AGPs/pull/97): Closed by AGP editor. No comment.
- [AGP PR 96](https://github.com/aragon/AGPs/pull/96): Closed by AGP editor. No comment.
- [AGP PR 95](https://github.com/aragon/AGPs/pull/95): Closed by AGP editor. No comment.
- [AGP PR 94](https://github.com/aragon/AGPs/pull/94): Closed by AGP editor due to lack of "finalization," even thought there is no clear documented protocol to "finalize" an AGP.
- [AGP PR 93](https://github.com/aragon/AGPs/pull/93): 7 days before "finalization" deadline AGP editor asked author to split PR into 2 because it contained multiple AGPs in the same PR. Author replied and followed instructions accordingly.
- [AGP PR 92](https://github.com/aragon/AGPs/pull/92): The AA and AGP editors made comments 10 hours before the "finalization" deadline. Author has commented in this thread that, due to their time zone, they were literally asleep when AA and AGP editors commented and had no way to reply before the deadline. AGP editor closed the AGP due to not being "finalized," even though there is no clear documented protocol to "finalize" an AGP. 
- [AGP PR 91](https://github.com/aragon/AGPs/pull/91): Comments were made by an AA member 10 hours before the "finalization" deadline. AGP editor closed the AGP due to not being "finalized," even though there is no clear documented protocol to "finalize" an AGP.
- [AGP PR 90](https://github.com/aragon/AGPs/pull/90): Comments were made by an AA member 10 hours before the "finalization" deadline. AGP editor closed the AGP due to not being "finalized," even though there is no clear documented protocol to "finalize" an AGP.
- [AGP PR 88](https://github.com/aragon/AGPs/pull/88): Comments were made by an AA member 10 hours before the "finalization" deadline. AGP editor closed the AGP due to not being "finalized," even though there is no clear documented protocol to "finalize" an AGP.
- [AGP PR 85](https://github.com/aragon/AGPs/pull/85): Comments were made by an AA member 10 hours before the "finalization" deadline. The author did their best to respond to comments in the time provided, but then could not edit their AGP due to a technical bug in the infrastructure used in the ANV governance process.
- [AGP PR 84](https://github.com/aragon/AGPs/pull/84): No comments. AGP editor closed the AGP due to not being "finalized," even though there is no clear documented protocol to "finalize" an AGP.
- [AGP PR 83](https://github.com/aragon/AGPs/pull/83): Review was provided by an AA member 10 hours before the "finalization" deadline. AGP editor closed the AGP due to not being "finalized," even though there is no clear documented protocol to "finalize" an AGP.
- [AGP PR 81](https://github.com/aragon/AGPs/pull/81): Review was provided by an AA member 10 hours before the "finalization" deadline. AGP editor closed the AGP due to not being "finalized," even though there is no clear documented protocol to "finalize" an AGP.

In all of these cases the AA provided feedback less than 24 hours before the AGP "finalization" deadline. There was a week for community review when such comments could have been made. Making comments less than 24 hours before a deadline is simply not enough time for AGP authors to reflect, respond, and make changes - esp in a global community that with differing time zones. This is inconsiderate and irresponsible at best, and downright mischievous as worst. How can we [fight for freedom](https://github.com/aragon/AGPs/blob/master/AGPs/AGP-0.md) if the very process we use to engage in Aragon community governance is so deeply biased and inefficient?

In all of these cases the process to "finalize" an AGP was not specified. No warnings or guidance was provided. AGPs were simply closed due to not complying with rules that were not specified in the first place. 
 
In many of these cased the PR mechanism for GitHub was broken and did not allow AGP authors to edit their AGPs. This prevented all governance participants from having fair and equal opportunity. This is not in line with [AGP-0](https://github.com/aragon/AGPs/blob/master/AGPs/AGP-0.md). 

<br>

## Call To Action
[AGP-1](https://github.com/aragon/AGPs/blob/master/AGPs/AGP-1.md) specifies that the AA can hold emergency votes to delay or reschedule Aragon Network Votes. For these reasons outlined in this Issue, I am calling for the AA to create an emergency vote push every stage of ANV4 back by 1 week. This will give everyone time to update their AGPs so that we can all get on the same page. This will update the ANV4 schedule to the following dates:

### Aragon Network Vote 4

* Draft proposals for this vote are due, mandatory community review period begins: **2019-10-10 at 16:00 UTC**
* Final draft proposals for this vote are due, Aragon Association review begins: **2019-10-17 at 16:00 UTC**
* Aragon Association review ends, final community review begins: **2019-10-24 at 16:00 UTC**
* Aragon Network Vote 4 begins: **2019-10-31 at 16:00 UTC**
* Aragon Network Vote 4 ends, final results announced: **2019-11-02 at 16:00 UTC**

<br>

## Summary
Aragon exists to [fight for freedom](https://github.com/aragon/AGPs/blob/master/AGPs/AGP-0.md), but this ANV did not support the freedoms of the Aragon community. This is because of a lack of specificity in AGP-1 around the AGP "finalization" process, GitHub technical difficulties that broke the infrastructure that facilitates the AGP process, and last min comments/review by AA that did not leave room for AGP authors to reflect, incorporate feedback, and update proposals before the AGP finalization deadline. As a result, all parties involved were not fairly represented and did not have an equal opportunity to participate in Aragon network governance. It is the responsibility of the AA to take action when things do not go according to plan. This is one of those times.   

@luisivan @izqui @stefanobernardi

**Comment by john-light** [comment]
Noting that there's a forum thread about this too: https://forum.aragon.org/t/call-for-an-emergency-vote-to-push-back-every-stage-of-anv4-by-1-week/1356/

I encourage people to keep their comments in that forum thread so as to keep the conversation happening in one place rather than scattering it around.

My reply is here: https://forum.aragon.org/t/call-for-an-emergency-vote-to-push-back-every-stage-of-anv4-by-1-week/1356/11

**Comment by burrrata** [comment]
The [Aragon Forum thread around this Issue](https://forum.aragon.org/t/call-for-an-emergency-vote-to-push-back-every-stage-of-anv4-by-1-week/1356/) is a great place for community discussions. 

This Issue, however, is a specific call to action for the AA board to vote to re-schedule ANV4 by pushing all stages of the ANV4 AGP process back by a week. The process for re-scheduling is defined in [AGP-1: Aragon Network Votes: Emergency Vote](https://github.com/aragon/AGPs/blob/master/AGPs/AGP-1.md) and [has been used in the past when there were technical difficulties or other complications](https://github.com/aragon/AGPs/blob/master/emergency_votes/vote-1-1/20180102.md).

**Comment by burrrata** [comment]
[ANV4 has been delayed by 1 week](https://forum.aragon.org/t/anv-4-delay-announcement/1367) so this Issue can be closed. 

@john-light While there were various announcements made announcing the delay of ANV4, I don't see a file created in the [Emergency Votes](https://github.com/aragon/AGPs/tree/master/emergency_votes/vote-1-1) folder of this repo. It looks like a file was created for the past delay, however. How and when does the process of creating files in the emergency votes folder work?

**Comment by john-light** [comment]
@burrrata good call, the announcement was made everywhere but there. The file has been created here: https://github.com/aragon/AGPs/pull/121
