### ISSUE TITLE
Proposal for Aragon to participate in Edgeware Lockdrop

### ISSUE THREAD

**Issue by thomivy** [aragon/AGPs#31]
Hi Aragon!

Our team over at Commonwealth Labs has drafted a proposal that would allow Aragon to participate in the launch of our new WASM-runtime, on-chain governed network Edgeware. Besides strong value and mission alignment, we’d love to share more about why this makes sense for Aragon to consider - if you’re interested, check our draft -we’ll get the AMA scheduled soon too!

https://gist.github.com/thomivy/afeb7e8d24e0cf7ea83076693aa7f1ad

**Comment by luisivan** [comment]
Hey! Very interesting proposal. Just a heads up that this needs to be a PR to the repo (see https://github.com/aragon/AGPs/pull/28) as an example.

**Comment by thomivy** [comment]
Oop-thanks! Repaired!
https://github.com/aragon/AGPs/pull/35
