### ISSUE TITLE
Add a title to the AGP documents

### ISSUE THREAD

**Issue by bpierre** [aragon/AGPs#55]
Having the titles as actual headings in the document, rather than only in the metadata, could help to identify what AGP is being seen.

Before: 
![before](https://user-images.githubusercontent.com/36158/56909237-276cc300-6aa8-11e9-89e5-666737b6e6bc.png)

After:
![after](https://user-images.githubusercontent.com/36158/56909235-276cc300-6aa8-11e9-9dbc-5bc0e2faebab.png)

We could also have the identifier in the title:
![after-2](https://user-images.githubusercontent.com/36158/56909236-276cc300-6aa8-11e9-8023-8c048695dcf0.png)

**Comment by john-light** [comment]
that seems redundant 🤔

**Comment by bpierre** [comment]
It certainly is! :laughing: But considering that it is the main source to read AGPs not only for machines but also for humans, I think it is important to have a proper title, at least until we have a dedicated interface to browse AGPs. The “Title” column of the table is too easily skipped, and the secondary title can easily be seen as the main title.

**Comment by luisivan** [comment]
Yeah, it certainly makes it more readable
